class UserError(Exception):
    pass

class UserNotFoundError(UserError):
    pass
